server:
  port: 0

spring:
  application:
    name: aclient
  datasource:
    url: jdbc:postgresql://localhost:5432/a_banking
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"