spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/a_banking
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
